# Generated by Django 4.1.4 on 2023-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about_us_images")),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
                ("text_hy", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_hy", models.TextField(null=True)),
                ("additional_text", models.TextField()),
                ("additional_text_en", models.TextField(null=True)),
                ("additional_text_ru", models.TextField(null=True)),
                ("additional_text_hy", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("name_hy", models.CharField(max_length=100, null=True)),
                ("role", models.CharField(max_length=100)),
                ("role_en", models.CharField(max_length=100, null=True)),
                ("role_ru", models.CharField(max_length=100, null=True)),
                ("role_hy", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="team/")),
            ],
        ),
        migrations.CreateModel(
            name="WhatWeDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_ru", models.CharField(max_length=100, null=True)),
                ("title_hy", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_hy", models.TextField(null=True)),
                ("icon_code", models.CharField(max_length=10)),
            ],
        ),
    ]
